#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/deepseek_v4/modular_deepseek_v4.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_deepseek_v4.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# Copyright 2026 the HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
from huggingface_hub.dataclasses import strict

from ...configuration_utils import PreTrainedConfig
from ...modeling_rope_utils import RopeParameters
from ...utils import auto_docstring


DEEPSEEK_V4_LAYER_TYPES = (
    "compressed_sparse_attention",
    "heavily_compressed_attention",
)


@auto_docstring(checkpoint="deepseek-ai/DeepSeek-V4-Flash-Base")
@strict
class DeepseekV4Config(PreTrainedConfig):
    r"""
    DeepSeek-V4's hybrid attention follows the paper (Section 2.3): every block is one
    of three attention types — *Full Attention* (sliding-window only), *Compressed
    Sparse Attention* (CSA, Section 2.3.1) and *Heavily Compressed Attention* (HCA,
    Section 2.3.2). CSA compresses the KV cache by ``compress_rate_csa`` (m=4 in V4-
    Flash/Pro) and selects ``index_topk`` blocks per query via the Lightning Indexer;
    HCA applies a much heavier compression of ``compress_rate_hca`` (m'=128) and
    skips sparse selection. Both branches add a small uncompressed sliding-window
    branch for fine-grained locality.

    layer_types (`list[str]`): Per-layer attention schedule with values from
        ``{"sliding_attention", "compressed_sparse_attention", "heavily_compressed_attention"}``.
        V4-Flash defaults: 2× full + interleaved CSA / HCA.
    compress_rate_csa (`int`): m, the CSA compression rate (default 4).
    compress_rate_hca (`int`): m', the HCA compression rate (default 128).
    compress_rope_theta (`float`): RoPE base for the compressed branches (paired with
        ``rope_scaling`` for YaRN).
    hc_mult (`int`): Manifold-Constrained Hyper-Connection (mHC) expansion factor n_hc
        (always active; Section 2.2).
    hc_sinkhorn_iters (`int`): Sinkhorn-Knopp iterations t_max for the mHC residual
        mapping projection onto doubly-stochastic matrices.
    hc_eps (`float`): Numerical floor for the Sinkhorn-Knopp normalization.
    num_hash_layers (`int`): First N MoE layers route via a frozen ``tid2eid[input_ids]`` lookup.
    scoring_func (`str`): Router activation — ``sqrtsoftplus``, ``softmax``, or ``sigmoid``.
    swiglu_limit (`float`): Clip routed experts' gate/up pre-activations.
    sliding_window (`int`): Local window size n_win used in every attention block's
        sliding-window branch.
    o_groups (`int`), o_lora_rank (`int`): Grouped low-rank output projection (g, d_g).
    index_n_heads, index_head_dim, index_topk (`int`): Lightning Indexer hyperparameters.
    num_nextn_predict_layers (`int`): MTP layer count in the upstream checkpoint (not instantiated here).
    """

    model_type = "deepseek_v4"
    keys_to_ignore_at_inference = ["past_key_values"]

    base_model_tp_plan = {
        "layers.*.self_attn.wq_a": "colwise",
        "layers.*.self_attn.wq_b": "colwise",
        "layers.*.self_attn.wkv": "colwise",
        "layers.*.self_attn.wo_a": "rowwise",
        "layers.*.self_attn.wo_b": "rowwise",
        "layers.*.mlp.experts.gate_up_proj": "packed_colwise",
        "layers.*.mlp.experts.down_proj": "rowwise",
        "layers.*.mlp.experts": "moe_tp_experts",
        "layers.*.mlp.shared_experts.gate_proj": "colwise",
        "layers.*.mlp.shared_experts.up_proj": "colwise",
        "layers.*.mlp.shared_experts.down_proj": "rowwise",
    }
    base_model_pp_plan = {
        "embed_tokens": (["input_ids"], ["inputs_embeds"]),
        "layers": (["hidden_states", "attention_mask"], ["hidden_states"]),
        "norm": (["hidden_states"], ["hidden_states"]),
    }
    attribute_map = {"num_local_experts": "n_routed_experts"}

    vocab_size: int = 129280
    hidden_size: int = 4096
    intermediate_size: int = 18432
    moe_intermediate_size: int = 2048
    num_hidden_layers: int = 43
    num_attention_heads: int = 64
    num_key_value_heads: int = 1
    n_shared_experts: int = 1
    n_routed_experts: int = 256
    routed_scaling_factor: float = 1.5

    # V3 fields kept ``None`` so MLA paths in inherited configs never fire.
    kv_lora_rank: int | None = None
    q_lora_rank: int = 1024
    qk_rope_head_dim: int = 64
    v_head_dim: int | None = None
    qk_nope_head_dim: int | None = None
    n_group: int | None = None
    topk_group: int | None = None
    num_experts_per_tok: int = 6
    first_k_dense_replace: int | None = None
    norm_topk_prob: bool = True
    hidden_act: str = "silu"
    max_position_embeddings: int = 1048576
    initializer_range: float = 0.02
    rms_norm_eps: float = 1e-6
    use_cache: bool = True
    pad_token_id: int | None = None
    bos_token_id: int | None = 0
    eos_token_id: int | list[int] | None = 1
    pretraining_tp: int | None = 1
    tie_word_embeddings: bool = False

    rope_parameters: RopeParameters | dict | None = None
    rope_interleave: bool | None = True
    attention_bias: bool = False
    attention_dropout: float = 0.0
    head_dim: int = 512
    scoring_func: str = "sqrtsoftplus"
    rope_theta: float = 10000.0

    layer_types: list[str] | None = None
    compress_rate_csa: int = 4
    compress_rate_hca: int = 128
    compress_rope_theta: float = 160000.0
    hc_mult: int = 4
    hc_sinkhorn_iters: int = 20
    hc_eps: float = 1.0e-6
    num_hash_layers: int = 3
    swiglu_limit: float = 10.0
    sliding_window: int = 128
    o_groups: int = 8
    o_lora_rank: int = 1024
    index_n_heads: int = 64
    index_head_dim: int = 128
    index_topk: int = 512
    num_nextn_predict_layers: int = 1

    output_router_logits: bool = False
    router_aux_loss_coef: float = 0.001
    router_jitter_noise: float = 0.0
    partial_rotary_factor: float | None = None

    def __post_init__(self, **kwargs):
        super().__post_init__(**kwargs)
        n = self.num_hidden_layers
        if self.layer_types is None:
            # V4-Pro default: two HCA bootstrap layers, then CSA / HCA interleaved.
            interleave = [
                "compressed_sparse_attention" if i % 2 else "heavily_compressed_attention"
                for i in range(max(n - 2, 0))
            ]
            head = ["heavily_compressed_attention"] * min(n, 2)
            self.layer_types = head + interleave
        self.layer_types = list(self.layer_types[:n])
        if len(self.layer_types) != n:
            raise ValueError(f"`layer_types` must cover at least {n} layers, got {len(self.layer_types)}.")
        for layer_type in self.layer_types:
            if layer_type not in DEEPSEEK_V4_LAYER_TYPES:
                raise ValueError(f"Unsupported layer_type={layer_type!r}; expected one of {DEEPSEEK_V4_LAYER_TYPES}.")
        self.qk_nope_head_dim = self.head_dim - self.qk_rope_head_dim
        if self.partial_rotary_factor is None:
            self.partial_rotary_factor = self.qk_rope_head_dim / self.head_dim
        # Normalize rope_parameters into a per-layer-type dict ``{"main": {...}, "compress": {...}}``
        # (Gemma3 pattern). Idempotent across save/load: round-tripping preserves structure.
        rp = self.rope_parameters or {}
        if isinstance(rp.get("main"), dict) and isinstance(rp.get("compress"), dict):
            self.rope_parameters = {"main": rp["main"], "compress": rp["compress"]}
        else:
            main = {k: v for k, v in rp.items() if k not in ("main", "compress")}
            main.setdefault("rope_type", "default")
            main.setdefault("rope_theta", self.rope_theta)
            main["partial_rotary_factor"] = self.partial_rotary_factor
            compress = {**main, "rope_theta": self.compress_rope_theta}
            self.rope_parameters = {"main": main, "compress": compress}


__all__ = ["DeepseekV4Config"]
